// Writes THIRD_PARTY_NOTICES.md from the shipped dependency graph: production npm packages
// and the Rust crates linked into the macOS binary. `--check` exits 1 when the file is stale.
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "THIRD_PARTY_NOTICES.md");
const run = (cmd, args, cwd) => execFileSync(cmd, args, { cwd, encoding: "utf8", maxBuffer: 256 << 20 });

function licenseTexts(dir) {
  if (!dir || !existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => /^(licen[cs]e|copying|notice)/i.test(f))
    .sort()
    .map((f) => readFileSync(join(dir, f), "utf8").trim());
}

function npmPackages() {
  const byLicense = JSON.parse(run("pnpm", ["licenses", "list", "--prod", "--json"], root));
  return Object.values(byLicense).flat().flatMap((p) =>
    p.versions.map((version, i) => ({ name: p.name, version, license: p.license, url: p.homepage ?? "", texts: licenseTexts(p.paths[i]) })),
  );
}

function cratePackages() {
  const meta = JSON.parse(run("cargo", ["metadata", "--format-version", "1", "--filter-platform", "aarch64-apple-darwin"], join(root, "src-tauri")));
  const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
  const shipped = new Set();
  const stack = [meta.resolve.root];
  while (stack.length) {
    const id = stack.pop();
    if (shipped.has(id)) continue;
    shipped.add(id);
    for (const dep of nodes.get(id).deps) if (dep.dep_kinds.some((k) => k.kind === null)) stack.push(dep.pkg);
  }
  return meta.packages
    .filter((p) => shipped.has(p.id) && p.id !== meta.resolve.root)
    .map((p) => ({ name: p.name, version: p.version, license: p.license ?? "see repository", url: p.repository ?? p.homepage ?? "", texts: licenseTexts(dirname(p.manifest_path)) }));
}

function render(groups) {
  const texts = new Map();
  const ref = (t) => {
    if (!texts.has(t)) texts.set(t, `T${texts.size + 1}`);
    return texts.get(t);
  };
  const lines = ["# Third-party notices", "", "Readi includes the software listed below. Each entry names its license and the license texts its package ships, printed once each at the end. Generated by `node scripts/notices.mjs`; do not edit by hand.", ""];
  for (const [title, pkgs] of groups) {
    lines.push(`## ${title}`, "");
    for (const p of pkgs.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version))) {
      const refs = p.texts.map(ref).join(", ");
      lines.push(`- ${p.name} ${p.version}. ${p.license}.${refs ? ` Text: ${refs}.` : ""}${p.url ? ` ${p.url}` : ""}`);
    }
    lines.push("");
  }
  lines.push("## License texts", "");
  for (const [t, id] of texts) lines.push(`### ${id}`, "", "```text", t, "```", "");
  return lines.join("\n");
}

const text = render([["JavaScript packages", npmPackages()], ["Rust crates", cratePackages()]]);
if (process.argv.includes("--check")) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== text) {
    console.error("THIRD_PARTY_NOTICES.md is stale; run node scripts/notices.mjs");
    process.exit(1);
  }
} else {
  writeFileSync(out, text);
  console.log(`wrote ${out}`);
}
